### ISSUE TITLE
مشکل در نمایش تاریخ در Kendo UI  MVC Grid

### ISSUE THREAD

**Issue by arman-hpp** [VahidN/Mvc-App-Persian-DatePicker#1]
سلام. من یه گرید کندو توی پروژه ام دارم که که مد ویرایش هم داره. در مد ویرایش این کنترل مشکلی نداری ولی در مد نمایش تاریخ رو به به میلادی توی گرید نمایش میده. لطفا راهنماییم کنید که چه کنم؟

**Comment by VahidN** [comment]
<div dir="rtl">

مراجعه كنيد به مطلب ذيل در اين مورد بحث شده‌است
http://www.dotnettips.info/post/1909/
